# Generated by Django 4.2.11 on 2024-04-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='cost',
            field=models.IntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High')], default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(5, 'Excellent - 5 Stars'), (4, 'Good - 4 Stars'), (3, 'Ok - 3 Stars'), (2, 'Could Be Better - 2 Stars'), (1, 'Poor - 1 Star'), (0, 'Really Bad - 0 Stars')], default=5),
        ),
    ]
