# Generated by Django 4.2.11 on 2024-05-08 11:39

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_recipe_featured_image_review_featured_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='featured_image',
            new_name='featured_image_1',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='featured_image',
            new_name='featured_image_1',
        ),
        migrations.AddField(
            model_name='recipe',
            name='featured_image_2',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='featured_image_3',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='review',
            name='featured_image_2',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='review',
            name='featured_image_3',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
