# Generated by Django 4.2.11 on 2024-04-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_review_cost_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
